Fix integer dtype for index array in AETC legacy code
Use dtype=int for zeros(1) to prevent float promotion when hstacking
with integer covariate_subset, which caused np.ix_ to fail with
IndexError: arrays used as indices must be of integer (or boolean) type